spring:
  application:
    name: Olik-Assigment

#  JPA properties
  jpa:
    hibernate:
#  It's set to create-drop for testing db seeding
      ddl-auto: create-drop
    show-sql: true

  #  active profile setting
  profiles:
    active: dev

